### ISSUE TITLE
Where are you at so far?

### ISSUE THREAD

**Issue by jackyliu16** [jlogan03/catnip#11]
First of all, I want to apologize to you. I may not have used the right words. I'm a little edgy right now because of the dissertation thing and I need to implement simple contracting on bare metal apps.

I would like to know if you have achieved what you call UDP protocol contract issuing and service receiving.
Your project seems to be the only one claiming to implement this right now, but I noticed in your readme file that you didn't implement the main feature, and I wanted to know if you implemented this service. At least above the second floor？

**Comment by jlogan03** [comment]
I think you're looking for demikernel's internal network stack, which is also called catnip but was not google-indexed when this library was made: https://github.com/microsoft/demikernel .

**Comment by jackyliu16** [comment]
Thanks for the tip. I'll look into this one.
